//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbVolunteerHubEntities : DbContext
    {
        public dbVolunteerHubEntities()
            : base("name=dbVolunteerHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrators> Administrators { get; set; }
        public virtual DbSet<ContentBlocks> ContentBlocks { get; set; }
        public virtual DbSet<EventApplications> EventApplications { get; set; }
        public virtual DbSet<EventRegistrations> EventRegistrations { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsImages> NewsImages { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TestAnswers> TestAnswers { get; set; }
        public virtual DbSet<TestQuestions> TestQuestions { get; set; }
        public virtual DbSet<TestResults> TestResults { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<TestResultAnswers> TestResultAnswers { get; set; }
    }
}
