//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsImages
    {
        public int NewsImageID { get; set; }
        public Nullable<int> ContentBlockID { get; set; }
        public Nullable<int> ImageID { get; set; }
    
        public virtual ContentBlocks ContentBlocks { get; set; }
        public virtual Images Images { get; set; }
    }
}
