//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerHub.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResultAnswers
    {
        public int ResultAnswerID { get; set; }
        public int ResultID { get; set; }
        public int QuestionID { get; set; }
        public int AnswerID { get; set; }
    
        public virtual TestAnswers TestAnswers { get; set; }
        public virtual TestQuestions TestQuestions { get; set; }
        public virtual TestResults TestResults { get; set; }
    }
}
